import React,{useState} from 'react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid,Legend} from 'recharts';
import {Panel} from './components.jsx';
import {decimal,money,percent,download} from './data.js';

const colors={strategy:'#68d9ba',buy_hold:'#e9b66c',benchmark:'#8baaff'};
const cell=v=>{const text=String(v??'');return '"'+(/^[\s]*[=+@-]/.test(text)&&typeof v==='string'?"'"+text:text).replaceAll('"','""')+'"';};
export default function BacktestResults({result:r,hypothesis}){
  const [ledger,setLedger]=useState('strategy'),[page,setPage]=useState(0);
  const labels={strategy:r.settings.strategy==='sma'?`${r.settings.window}-session moving average`:'Selected buy and hold',buy_hold:'Same basket · buy and hold',benchmark:`${r.settings.benchmark} · buy and hold`};
  const s=r.runs.strategy.summary;
  const chart=r.runs.strategy.daily.map((d,i)=>({date:d.date,...Object.fromEntries(Object.entries(r.runs).flatMap(([k,run])=>[[k,run.daily[i].value],[k+'_drawdown',run.daily[i].drawdown]]))}));
  const trades=r.runs[ledger].trades,pageSize=40;
  function csv(kind){
    const metadata=[['Engine version',r.engine_version],['Hypothesis',hypothesis],['Source',r.settings.source],['Price basis',r.price_basis],['Data SHA-256',r.data_sha256],['Settings JSON',JSON.stringify(r.settings)],[]];
    let rows;
    if(kind==='trades'){
      const keys=['date','ticker','side','signal_date','signal_close','signal_average','reason','reference_open','fill_price','adjusted_units','notional','commission','slippage_cost','cash_after','closed_pnl'];
      rows=[['comparison',...keys],...Object.entries(r.runs).flatMap(([k,run])=>run.trades.map(t=>[k,...keys.map(c=>t[c])]))];
    }else rows=[['date','strategy_value','buy_hold_value','benchmark_value','strategy_drawdown','buy_hold_drawdown','benchmark_drawdown','strategy_cash','strategy_exposure'],...chart.map((d,i)=>[d.date,d.strategy,d.buy_hold,d.benchmark,d.strategy_drawdown,d.buy_hold_drawdown,d.benchmark_drawdown,r.runs.strategy.daily[i].cash,r.runs.strategy.daily[i].exposure])];
    download({name:`backtest_${kind}.csv`,mime:'text/csv',content:[...metadata,...rows].map(row=>row.map(cell).join(',')).join('\r\n')});
  }
  const lineChart=(drawdown=false)=><div role="img" aria-label={drawdown?'Backtest drawdowns':'Backtest portfolio value'} className="backtest-chart"><ResponsiveContainer width="100%" height={300}><LineChart data={chart} margin={{top:15,right:20,left:15,bottom:10}}><CartesianGrid stroke="#283340" strokeDasharray="3 3"/><XAxis dataKey="date" minTickGap={60}/><YAxis domain={drawdown?['auto',0]:['auto','auto']} tickFormatter={v=>drawdown?percent(v):'$'+decimal(v,0)} width={85}/><Tooltip formatter={(v,name)=>[drawdown?percent(v):money(v),name]} contentStyle={{background:'#111923',border:'1px solid #344255',color:'#dce5f1'}}/><Legend/>{Object.entries(labels).map(([k,label])=><Line key={k} type="linear" dataKey={k+(drawdown?'_drawdown':'')} name={label} stroke={colors[k]} strokeWidth={k==='strategy'?2.5:1.5} dot={false} isAnimationActive={false}/>)}</LineChart></ResponsiveContainer></div>;
  return <section className="backtest-results" aria-label="Backtest results">
    <div className="section-heading"><div><h2>{r.settings.source==='demo'?'Offline example results':'Historical simulation results'}</h2><p>{r.start} → {r.end} · {r.sessions} sessions · {r.warmup_sessions} warm-up sessions · Starting capital {money(r.settings.capital)}</p></div><div className="backtest-actions"><button onClick={()=>csv('daily')}>Download daily values</button><button onClick={()=>csv('trades')}>Download trades</button><button onClick={()=>download({name:'backtest_run.json',mime:'application/json',content:JSON.stringify({hypothesis,...r},null,2)})}>Download full run</button></div></div>
    <div className="backtest-summary" aria-label="Backtest strategy summary">{[['Final value',money(s.ending_value)],['Total return',percent(s.total_return)],['Maximum drawdown',percent(s.max_drawdown)],['Order count',String(s.orders)]].map(([name,value])=><div key={name}><span>{name}</span><strong>{value}</strong></div>)}</div>
    <Panel title="Portfolio value after costs">{lineChart()}<p className="note">All three start with {money(r.settings.capital)} at the first session’s open. The plotted values are end-of-session values after any trades and costs. The same basket uses your initial allocations; the benchmark invests 100% in {r.settings.benchmark}.</p></Panel>
    <Panel title="Drawdown from previous peak">{lineChart(true)}</Panel>
    <Panel title="Performance comparison"><div className="table-wrap"><table aria-label="Backtest performance comparison"><thead><tr><th>Metric</th>{Object.keys(labels).map(k=><th key={k} style={{color:colors[k]}}>{labels[k]}</th>)}</tr></thead><tbody>{[['ending_value','Final value',money],['pnl','Net profit / loss',money],['total_return','Total return',percent],['cagr','CAGR · ≥1 year',percent],['max_drawdown','Maximum drawdown',percent],['volatility','Annualized volatility',percent],['sharpe','Annualized Sharpe',decimal],['average_exposure','Average invested exposure',percent],['orders','Orders',v=>String(v)],['closed_trades','Closed trades',v=>String(v)],['win_rate','Closed-trade win rate',percent],['commissions','Commissions & fixed fees',money],['slippage_cost','Modeled slippage cost',money]].map(([k,title,format])=><tr key={k}><th scope="row">{title}</th>{Object.keys(labels).map(run=><td key={run}>{format(r.runs[run].summary[k])}</td>)}</tr>)}</tbody></table></div><p className="note">Costs are already reflected in returns. Slippage is embedded in execution prices; it is not subtracted twice. Open positions are marked to market without final exit fees. A blank win rate means no completed round trips.</p></Panel>
    <Panel title="Trade ledger" action={<label>Show trades for<select aria-label="Show trades for" value={ledger} onChange={e=>{setLedger(e.target.value);setPage(0);}}>{Object.entries(labels).map(([k,label])=><option key={k} value={k}>{label}</option>)}</select></label>}>
      <div className="table-wrap"><table aria-label="Backtest trade ledger"><thead><tr><th>Trade date</th><th>Ticker / side</th><th>Signal date</th><th>Signal close / average</th><th>Adjusted open</th><th>Fill price</th><th>Adjusted units</th><th>Fees</th><th>Slippage cost</th><th>Closed net P&amp;L</th></tr></thead><tbody>{trades.slice(page*pageSize,(page+1)*pageSize).map((t,i)=><tr key={i}><td>{t.date}</td><td><strong>{t.ticker}</strong><span className={t.side==='BUY'?'positive':'negative'}> {t.side}</span></td><td>{t.signal_date||'Initial allocation'}</td><td>{t.signal_date?`${decimal(t.signal_close,4)} / ${decimal(t.signal_average,4)}`:'—'}</td><td>{decimal(t.reference_open,4)}</td><td>{decimal(t.fill_price,4)}</td><td>{decimal(t.adjusted_units,6)}</td><td>{money(t.commission)}</td><td>{money(t.slippage_cost)}</td><td>{money(t.closed_pnl)}</td></tr>)}{trades.length===0&&<tr><td colSpan={10} className="empty-row">No orders: this strategy remained in cash during the selected period.</td></tr>}</tbody></table></div>
      <div className="panel-head"><span className="muted small">{trades.length} orders · Showing {trades.length?Math.min(page*pageSize+1,trades.length):0}–{Math.min((page+1)*pageSize,trades.length)}. Quantities and prices use the adjusted scale.</span><div className="backtest-actions"><button disabled={page===0} onClick={()=>setPage(n=>n-1)}>Previous orders</button><button disabled={(page+1)*pageSize>=trades.length} onClick={()=>setPage(n=>n+1)}>Next orders</button></div></div>
    </Panel>
    <Panel title="Ending strategy positions"><div className="table-wrap"><table aria-label="Backtest ending positions"><thead><tr><th>Ticker</th><th>Adjusted units</th><th>Market value</th><th>Uninvested cash</th></tr></thead><tbody>{r.runs.strategy.ending_positions.map(p=><tr key={p.ticker}><th scope="row">{p.ticker}</th><td>{decimal(p.units,6)}</td><td>{money(p.market_value)}</td><td>{money(p.cash)}</td></tr>)}</tbody></table></div></Panel>
    <details className="warnings" open><summary>Run assumptions & data audit</summary><ul>{r.warnings.map(w=><li key={w}>{w}</li>)}</ul><p>Source: {r.settings.source==='demo'?'Deterministic invented example':'Yahoo Finance through yfinance'}. Price basis: {r.price_basis}. {r.market_data_fetched_at&&`Fetched: ${r.market_data_fetched_at}.`} Calculated: {r.calculated_at||'Offline engine'}.</p>{r.identities?.length>0&&<p>{r.identities.map(i=>`${i.ticker}: ${i.name} (${i.exchange}, ${i.currency})`).join(' · ')}</p>}<p className="backtest-hash">Data fingerprint: {r.data_sha256}</p><p>Full-run JSON contains all input settings, warm-up prices, daily results, trades and skipped orders for every comparison.</p></details>
  </section>;
}
