import React from 'react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid,ReferenceLine} from 'recharts';
import {Panel} from './components.jsx';
import {decimal,download} from './data.js';

export default function BondResults({result:r,inputs:b}){
  const number=(v,n=4)=>decimal(v,n),money=v=>Number.isFinite(v)?new Intl.NumberFormat('en-US',{style:'currency',currency:r.currency,maximumFractionDigits:2}).format(v):'—';
  function exportCsv(){
    const rows=[['Bond Analytics',r.name],['Model version',r.model_version],['Input','Value'],...Object.entries(b),[],['Result','Value'],...Object.entries(r).filter(([,v])=>v===null||typeof v!=='object'),[],['Schedule convention','Value'],...Object.entries(r.audit),[],['Payment date','Coupon / 100','Principal / 100','Remaining periods','Cash flow (position)','Discount factor','Present value (position)']];
    for(const c of r.cashflows)rows.push([c.date,c.coupon_per_100,c.principal_per_100,c.periods,c.position_cashflow,c.discount_factor,c.present_value]);
    rows.push([],['Yield change (bp)','Yield (%)','Clean / 100','Dirty / 100','Settlement value','Change','Change (%)','Duration + convexity approximation']);for(const s of r.shocks)rows.push([s.shift_bps,s.yield_percent,s.clean_price,s.dirty_price,s.position_value,s.change,s.change_percent,s.approx_change]);
    if(r.spread_grid){rows.push([],['Benchmark (%) / spread (bp)',...r.spread_grid.columns]);for(const row of r.spread_grid.rows)rows.push([row.benchmark,...row.values]);}
    rows.push([],['Scope','Regular non-callable bullet bond; promised payments, constant yield, no default/recovery/fees/taxes.'],...r.warnings.map(w=>['Warning',w]));
    const escape=v=>'"'+(typeof v==='string'&&/^[=+@-]/.test(v)?"'":'')+String(v??'').replaceAll('"','""')+'"';
    download({name:'bond-calculation-audit.csv',mime:'text/csv',content:rows.map(row=>row.map(escape).join(',')).join('\n')});
  }
  return <div className="analytics-results derivatives-results bond-results">
    <div className="section-heading"><div><h2>Bond results{r.name?' · '+r.name:''}</h2><p>{r.settlement} settlement · {r.currency} · principal repaid at par</p></div><div className="analytics-export"><button onClick={exportCsv}>Download bond CSV</button><button onClick={()=>download({name:'bond-model.json',mime:'application/json',content:JSON.stringify({inputs:b,result:r},null,2)})}>Download bond model</button></div></div>
    {r.warnings.map(w=><p className="banner" key={w}>{w}</p>)}
    <div className="options-summary" aria-label="Bond price summary">{[['Clean price / 100',number(r.clean_price)],['Accrued interest / 100',number(r.accrued_per_100)],['Dirty price / 100',number(r.dirty_price)],['Yield to maturity',number(r.yield_percent)+'%']].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
    <Panel title="Position value"><div className="analytics-audit-summary">{[['Clean position value',money(r.clean_value)],['Accrued interest payable',money(r.accrued_amount)],['Cash at settlement',money(r.settlement_value)],['Coupon each payment',money(r.coupon_payment)],['Annual coupon income',money(r.annual_coupon)],['Current yield at model price',number(r.current_yield)+'%']].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><p className="note">Clean value + accrued interest = cash at settlement, before fees and taxes. Current yield is annual coupon divided by clean price; it excludes the maturity gain or loss. Yield to maturity is nominal annual yield at the chosen frequency. Its equivalent annual compounded rate is {number(r.effective_annual_yield)}%.</p></Panel>
    {r.market_gap!==null&&<Panel title="Entered market price"><div className="analytics-audit-summary"><div><span>Market yield to maturity</span><strong>{r.market_yield_percent===null?'Unavailable':number(r.market_yield_percent)+'%'}</strong></div><div><span>Market minus model clean price / 100</span><strong>{number(r.market_gap)}</strong></div><div><span>Cash cost at entered market price</span><strong>{money(r.market_settlement_value)}</strong></div></div><p className="note">{b.mode==='yield'?'The model solves the yield that reproduces your entered clean price plus accrued interest.':'A price gap reflects the difference between the entered quote and your discount-yield assumption; it is not an arbitrage profit.'} {r.yield_solver_residual!==null&&<>Yield solver price residual: {r.yield_solver_residual.toExponential(2)} per 100.</>}</p></Panel>}
    <Panel title="Interest-rate sensitivity"><div className="options-summary bond-risk" aria-label="Bond risk summary">{[['Macaulay duration',number(r.macaulay_duration)+' years'],['Modified duration',number(r.modified_duration)+' years'],['Convexity',number(r.convexity)+' years²'],['Position DV01',money(r.dv01)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><p className="note">A +1 percentage-point yield change gives an approximate {number(r.modified_duration,2)}% price fall using duration alone. DV01 is the approximate position loss for +1 basis point (0.01 percentage point). These measures use dirty price and fixed promised cash flows.</p>
      <div className="bond-price-chart" role="img" aria-label="Bond clean price versus yield"><ResponsiveContainer width="100%" height={280}><LineChart data={r.shocks} margin={{top:12,right:25,left:0,bottom:28}}><CartesianGrid stroke="#283340" strokeDasharray="3 3"/><XAxis dataKey="yield_percent" type="number" domain={['dataMin','dataMax']} tickFormatter={v=>number(v,2)} label={{value:'Annual yield (%)',position:'insideBottom',offset:-18}}/><YAxis domain={['auto','auto']} tickFormatter={v=>number(v,1)} width={70}/><Tooltip formatter={v=>[number(v),'Clean price / 100']} labelFormatter={v=>`Yield ${number(v)}%`} contentStyle={{background:'#111923',border:'1px solid #344255',color:'#dce5f1'}}/><ReferenceLine x={r.yield_percent} stroke="#8baaff" strokeDasharray="4 4"/><Line type="monotone" dataKey="clean_price" stroke="#e9b66c" strokeWidth={2} dot={{r:3}} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>
      <div className="table-wrap"><table aria-label="Bond yield shocks"><thead><tr><th>Yield change</th><th>Yield</th><th>Clean / 100</th><th>Position change</th><th>Change / dirty value</th><th>Duration + convexity estimate</th></tr></thead><tbody>{r.shocks.map(s=><tr key={s.shift_bps} className={s.shift_bps===0?'bond-base-row':''}><th scope="row">{s.shift_bps>0?'+':''}{s.shift_bps} bp</th><td>{number(s.yield_percent,2)}%</td><td>{number(s.clean_price)}</td><td>{money(s.change)}</td><td>{number(s.change_percent,2)}%</td><td>{money(s.approx_change)}</td></tr>)}</tbody></table></div><p className="note">Full repricing at the same settlement date. These are instantaneous changes in value, not holding-period returns. The approximation uses −modified duration × Δyield + ½ × convexity × Δyield². Larger shocks can produce greater approximation error.</p>
    </Panel>
    {r.spread_grid&&<Panel title="Benchmark × credit-spread scenarios"><div className="table-wrap"><table className="sensitivity-table" aria-label="Bond credit spread sensitivity"><thead><tr><th>Benchmark ↓ / spread →</th>{r.spread_grid.columns.map(c=><th key={c}>{number(c,0)} bp</th>)}</tr></thead><tbody>{r.spread_grid.rows.map(row=><tr key={row.benchmark}><th scope="row">{number(row.benchmark,2)}%</th>{row.values.map((v,i)=><td key={i} className={row.benchmark===Number(b.benchmark_yield)&&r.spread_grid.columns[i]===Number(b.spread_bps)?'pricing-base-cell':''}>{number(v)}</td>)}</tr>)}</tbody></table></div><p className="note">Clean prices per 100. Benchmark and spread changes add to the same flat discount yield, so equal combined yield changes produce equal prices. This does not independently model credit losses or a term structure.</p></Panel>}
    <Panel title="Cash-flow audit"><div className="analytics-audit-summary">{[['Previous coupon',r.audit.previous_coupon],['Next coupon',r.audit.next_coupon],['Remaining payments',String(r.audit.remaining_payments)],['Elapsed / period days',`${r.audit.elapsed_days} / ${r.audit.period_days}`],['Accrued coupon fraction',number(r.audit.accrued_fraction,6)],['Next-payment fraction',number(r.audit.remaining_fraction,6)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><p className="note">{r.audit.day_count==='actual_actual'?'Actual days within the coupon period.':'Adjusted US 30/360 day counts.'} {r.audit.simple_final_used?'Simple interest applies to the single remaining payment.':'Discounting uses fractional-period compounding.'} On settlement dates that are coupon dates, that coupon is excluded and accrued interest starts at zero. Payment dates are unadjusted.</p>
      <div className="table-wrap bond-cashflows"><table aria-label="Bond cash flows"><thead><tr><th>Payment date</th><th>Coupon / 100</th><th>Principal / 100</th><th>Remaining periods</th><th>Position cash flow</th><th>Discount factor</th><th>Present value</th></tr></thead><tbody>{r.cashflows.map(c=><tr key={c.date}><th scope="row">{c.date}</th><td>{number(c.coupon_per_100)}</td><td>{number(c.principal_per_100)}</td><td>{number(c.periods,6)}</td><td>{money(c.position_cashflow)}</td><td>{number(c.discount_factor,8)}</td><td>{money(c.present_value)}</td></tr>)}</tbody><tfoot><tr><th colSpan={6}>Total discounted cash flows · cash at settlement</th><td>{money(r.settlement_value)}</td></tr></tfoot></table></div>
    </Panel>
  </div>;
}
