import React,{useState} from 'react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid,Legend} from 'recharts';
import {Panel} from './components.jsx';
import {decimal,money,percent,download} from './data.js';

const eventNames={BUY_STOCK:'Buy stock',DISTRIBUTION:'Stock distribution',SELL_CALL:'Write call',ASSIGN:'Deliver stock at strike',EXPIRE:'Call expires',BUY_CALL_TO_ROLL:'Buy back call to roll',SKIP_ROLL:'Roll skipped',SKIP_CALL:'Call skipped',SKIP_STOCK:'Stock purchase skipped'};
const csvCell=v=>{let s=String(v??'');if(typeof v==='string'&&/^\s*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};
export default function CoveredCallResults({result:r,hypothesis}){
  const [page,setPage]=useState(0),[cyclePage,setCyclePage]=useState(0);
  const cc=r.covered_call,stock=r.stock_only,s=cc.summary;
  const chart=cc.daily.map((d,i)=>({date:d.date,covered:d.value,stock:stock.daily[i].value,covered_dd:d.drawdown,stock_dd:stock.daily[i].drawdown}));
  function exportCsv(){
    const rows=[['Result type',r.result_type],['Option prices',r.option_price_source],['Hypothesis',hypothesis],['Settings',JSON.stringify(r.settings)],['Data SHA-256',r.data_sha256],[],['Metric','Covered call','Stock only'],...Object.keys(s).map(k=>[k,s[k],stock.summary[k]]),[],['Date','Covered-call value','Stock-only value','Cash','Stock units','Stock value','Short-call liability','Covered-call drawdown','Stock-only drawdown'],...cc.daily.map((d,i)=>[d.date,d.value,stock.daily[i].value,d.cash,d.shares,d.stock_value,d.call_liability,d.drawdown,stock.daily[i].drawdown]),[],['Cycle','Entry','Expiry in range','Strike','Contracts','Assumed IV (%)','Model premium/unit','Fill premium/unit','Premium received','Entry fee','Exit date','Status','Exit option value','Exit fee','Option P&L'],...cc.cycles.map(c=>[c.cycle,c.entry_date,c.expiry_date,c.strike,c.contracts,c.assumed_iv,c.model_entry,c.fill_entry,c.premium_received,c.entry_fee,c.exit_date,c.status,c.exit_value,c.exit_fee,c.option_pnl]),[],['IV shift (pp)','Cost multiplier','Net return','Final value','Error'],...r.sensitivity.flatMap(row=>row.values.map(v=>[row.iv_shift_pp,v.cost_multiplier,v.total_return,v.ending_value,v.error])),[],['Strategy','Date','Event','Cash change','Fee','Cash after','Stock units after','Details'],...[['covered_call',cc],['stock_only',stock]].flatMap(([name,run])=>run.events.map(e=>[name,e.date,e.event,e.cash_change,e.fee,e.cash_after,e.shares_after,JSON.stringify(e)]))];
    download({name:'covered_call_MODELED_simulation.csv',mime:'text/csv',content:rows.map(row=>row.map(csvCell).join(',')).join('\r\n')});
  }
  const lineChart=dd=><div className="backtest-chart" role="img" aria-label={dd?'Covered-call drawdowns':'Covered-call versus stock value'}><ResponsiveContainer width="100%" height={290}><LineChart data={chart} margin={{top:15,right:20,left:15,bottom:10}}><CartesianGrid stroke="#283340" strokeDasharray="3 3"/><XAxis dataKey="date" minTickGap={60}/><YAxis width={85} domain={dd?['auto',0]:['auto','auto']} tickFormatter={v=>dd?percent(v):'$'+decimal(v,0)}/><Tooltip formatter={v=>dd?percent(v):money(v)} contentStyle={{background:'#111923',border:'1px solid #344255',color:'#dce5f1'}}/><Legend/><Line type="linear" dataKey={dd?'covered_dd':'covered'} name="Covered call · modeled" stroke="#68d9ba" strokeWidth={2.5} dot={false} isAnimationActive={false}/><Line type="linear" dataKey={dd?'stock_dd':'stock'} name="Same stock position" stroke="#e9b66c" strokeWidth={1.7} dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>;
  return <section className="backtest-results" aria-label="Covered-call simulation results">
    <div className="section-heading"><div><h2>Modeled covered-call results</h2><p>{r.settings.source==='demo'?'Invented stock history':'Downloaded stock history'} · {r.start} → {r.end} · {r.sessions} sessions · {r.settings.contracts*100} stock units</p></div><div className="backtest-actions"><button onClick={exportCsv}>Download simulation CSV</button><button onClick={()=>download({name:'covered_call_MODELED_run.json',mime:'application/json',content:JSON.stringify({hypothesis,...r},null,2)})}>Download complete simulation</button></div></div>
    <div className="backtest-summary" aria-label="Covered-call summary">{[['Final net value',money(s.ending_value)],['Total return',percent(s.total_return)],['Versus stock only',money(s.ending_value-stock.summary.ending_value)],['Maximum drawdown',percent(s.max_drawdown)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
    <Panel title="Net portfolio value after costs">{lineChart(false)}<p className="note">Cash + stock value − short-call liability. Both paths start with {money(r.settings.capital)}, buy the same stock quantity and leave unused capital in cash. Premiums are retained, not used to increase the position.</p></Panel>
    <Panel title="Declines from previous peak">{lineChart(true)}</Panel>
    <Panel title="Stock ownership versus covered calls"><div className="table-wrap"><table aria-label="Covered-call performance comparison"><thead><tr><th>Metric</th><th>Covered call · modeled</th><th>Stock only</th></tr></thead><tbody>{[['ending_value','Final net value',money],['pnl','Net profit / loss',money],['total_return','Total return',percent],['cagr','CAGR · ≥1 year',percent],['max_drawdown','Maximum drawdown',percent],['volatility','Annualized volatility',percent],['sharpe','Sharpe · 0% reference',decimal],['premium_received','Gross premiums received',money],['distributions','Stock distributions credited',money],['fees','Fees paid',money],['slippage_cost','Modeled spread & slippage cost',money],['assignments','Expiry assignments',String],['rolls','Early rolls completed',String],['calls_written','Option contracts written',String],['skipped_actions','Skipped actions',String]].map(([key,label,format])=><tr key={key}><th scope="row">{label}</th><td>{format(s[key])}</td><td>{format(stock.summary[key])}</td></tr>)}</tbody></table></div><p className="note">Gross premiums are not profit. Fees and spreads are already reflected in the net results, and unexpired calls remain liabilities. Assignment can cap gains; stock losses remain possible.</p></Panel>
    <Panel title="How much do the assumptions matter?"><div className="table-wrap"><table aria-label="Covered-call volatility and cost sensitivity"><thead><tr><th>Volatility change ↓ / Costs →</th><th>0× costs</th><th>1× entered costs</th><th>2× costs</th></tr></thead><tbody>{r.sensitivity.map(row=><tr key={row.iv_shift_pp}><th scope="row">{row.iv_shift_pp>0?'+':''}{row.iv_shift_pp} percentage points</th>{row.values.map(v=><td key={v.cost_multiplier} className={row.iv_shift_pp===0&&v.cost_multiplier===1?'simulation-base-cell':''}>{v.error?<span title={v.error}>Unavailable: {v.error}</span>:<><strong>{percent(v.total_return)}</strong><span className="company">{money(v.ending_value)} final value</span></>}</td>)}</tr>)}</tbody></table></div><p className="note">Each cell reruns the full covered-call strategy. Costs include stock fees/slippage, option spreads/fees and assignment fees. Volatility is floored at 0% and capped at 300%. The highlighted cell is your base case. These are assumption scenarios, not probabilities or confidence intervals.</p></Panel>
    <Panel title="Call-cycle audit"><div className="table-wrap"><table aria-label="Simulated call cycles"><thead><tr><th>Cycle</th><th>Entry / expiry</th><th>Strike</th><th>Assumed IV</th><th>Model / sold premium per unit</th><th>Gross premium</th><th>Status / exit</th><th>Closed option contribution</th></tr></thead><tbody>{cc.cycles.slice(cyclePage*25,(cyclePage+1)*25).map(c=><tr key={c.cycle}><th scope="row">{c.cycle}</th><td>{c.entry_date}<span className="company">{c.expiry_date||'Expiry beyond test'}</span></td><td>{money(c.strike)}</td><td>{decimal(c.assumed_iv)}%</td><td>{decimal(c.model_entry,4)} / {decimal(c.fill_entry,4)}</td><td>{money(c.premium_received)}</td><td>{c.status}<span className="company">{c.exit_date||'Marked, not closed'}</span></td><td>{money(c.option_pnl)}</td></tr>)}{!cc.cycles.length&&<tr><td colSpan={8}>No calls written; inspect skipped actions in the ledger.</td></tr>}</tbody></table></div><div className="panel-head"><span className="muted small">{cc.cycles.length} synthetic call cycles · Closed option contribution excludes stock P&amp;L. For assignments it deducts foregone upside as intrinsic value; that is not a second cash payment.</span><div className="backtest-actions"><button disabled={cyclePage===0} onClick={()=>setCyclePage(p=>p-1)}>Previous calls</button><button disabled={(cyclePage+1)*25>=cc.cycles.length} onClick={()=>setCyclePage(p=>p+1)}>Next calls</button></div></div></Panel>
    <Panel title="Cash & stock ledger"><div className="table-wrap"><table aria-label="Covered-call cash ledger"><thead><tr><th>Date</th><th>Action</th><th>Cash change</th><th>Included fee</th><th>Cash after</th><th>Stock units after</th><th>Note</th></tr></thead><tbody>{cc.events.slice(page*40,(page+1)*40).map((e,i)=><tr key={i}><td>{e.date}</td><td>{eventNames[e.event]||e.event}</td><td>{money(e.cash_change)}</td><td>{money(e.fee)}</td><td>{money(e.cash_after)}</td><td>{e.shares_after}</td><td>{e.reason||(e.strike?`Strike ${money(e.strike)}`:'')}</td></tr>)}</tbody></table></div><div className="panel-head"><span className="muted small">{cc.events.length} events · Page {page+1} of {Math.max(1,Math.ceil(cc.events.length/40))}. All events are included in downloads.</span><div className="backtest-actions"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous events</button><button disabled={(page+1)*40>=cc.events.length} onClick={()=>setPage(p=>p+1)}>Next events</button></div></div></Panel>
    <Panel title="Ending account reconciliation"><div className="backtest-summary">{[['Cash',money(s.ending_cash)],['Stock value',money(cc.daily.at(-1).stock_value)],['Less: short-call liability',money(s.ending_liability)],['Net account value',money(s.ending_value)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><p className="note">{s.ending_shares} stock units remain. Open positions are marked at model values without final sale, buyback or closing fees.</p></Panel>
    <details className="warnings"><summary>Model assumptions & data audit</summary><ul>{r.warnings.map(w=><li key={w}>{w}</li>)}</ul><p>{r.option_price_source}. Stock basis: {r.stock_price_basis}.</p><p>{r.identity&&`${r.identity.ticker}: ${r.identity.name} (${r.identity.exchange}). `}{r.market_data_fetched_at&&`Stock history fetched ${r.market_data_fetched_at}. `}Calculated {r.calculated_at||'offline'}.</p><p className="backtest-hash">Stock-data fingerprint: {r.data_sha256}</p></details>
  </section>;
}
