import React from 'react';
import {Panel} from './components.jsx';
import {decimal,download} from './data.js';

const greekLabels={delta:'Delta',gamma:'Gamma',theta:'Theta / day',vega:'Vega / 1pp',rho:'Rho / 1pp'};
const greekUnits={delta:'Price change per +1 spot unit',gamma:'Delta change per +1 spot unit',theta:'Price change per day elapsed',vega:'Price change per +1 percentage point volatility',rho:'Price change per +1 percentage point interest rate'};
export default function DerivativesResults({type,result:r,inputs:a}){
  const option=type==='option',c=r.convergence;
  const number=v=>Number.isFinite(v)?decimal(v,6):'—';
  const money=v=>Number.isFinite(v)?new Intl.NumberFormat('en-US',{style:'currency',currency:r.currency,maximumFractionDigits:2}).format(v):'—';
  const totals=option?[['Model premium / unit',number(r.unit_price)],['Premium / contract',money(r.per_contract)],['Total premium',money(r.total_premium)],['Intrinsic / unit',number(r.intrinsic)]]:[['Theoretical delivery price',number(r.unit_price)],['Basis · delivery minus spot',number(r.basis)],['Notional / contract',money(r.per_contract_notional)],['Total notional',money(r.total_notional)]];
  const audit=option?[['Discounted spot',r.audit.discounted_spot],['Discounted strike',r.audit.discounted_strike],['Spot discount factor',r.audit.spot_discount],['Strike discount factor',r.audit.strike_discount],['European d₁',r.audit.d1],['European d₂',r.audit.d2]]:[['Net annual carry (%)',r.carry_percent],['Carry exponent',r.audit.exponent],['Carry factor',r.carry_factor],['Spot sensitivity',r.spot_sensitivity],['Rate sensitivity / 1pp',r.rate_sensitivity]];
  function exportCsv(){
    const rows=[['Model',r.model],['Model version',r.model_version],['Quote currency',r.currency],['Input','Value'],...Object.entries(a),[],['Output','Value'],...Object.entries(r).filter(([,v])=>v===null||typeof v!=='object'),[],['Audit item','Value'],...Object.entries(r.audit)];
    if(r.greeks)rows.push([],['Greek (per option unit)','Value'],...Object.entries(r.greeks).map(([k,v])=>[greekLabels[k],v]));
    if(c)rows.push([],['Tree check','Value'],...Object.entries(c));
    rows.push([],['Spot / '+(option?'annual volatility (%)':'funding rate (%)'),...r.sensitivity.columns]);for(const row of r.sensitivity.rows)rows.push([row.spot,...row.values]);
    rows.push([],['Limitations','Conditional model estimate; quote gaps are not trading profits. See full model scope in Analytics Lab.'],...r.warnings.map(w=>['Warning',w]));
    const escape=v=>'"'+(typeof v==='string'&&/^[=+@-]/.test(v)?"'":'')+String(v??'').replaceAll('"','""')+'"';
    download({name:type+'-pricing-audit.csv',mime:'text/csv',content:rows.map(row=>row.map(escape).join(',')).join('\n')});
  }
  return <div className="analytics-results derivatives-results">
    <div className="section-heading"><div><h2>Pricing results{a.symbol?' · '+a.symbol:''}</h2><p>{r.model} · {r.days} days · ACT/365 · {r.currency} quote basis</p></div><div className="analytics-export"><button onClick={exportCsv}>Download pricing CSV</button><button onClick={()=>download({name:type+'-pricing-model.json',mime:'application/json',content:JSON.stringify({inputs:a,result:r},null,2)})}>Download full pricing model</button></div></div>
    {r.warnings.map(w=><p className="banner" key={w}>{w}</p>)}
    <div className="options-summary" aria-label="Pricing summary">{totals.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
    <p className="note">{option?'Premiums represent the model cost of buying the entered number of contracts. They are not a payoff, return forecast or margin estimate.':'For index contracts, delivery price and basis are quoted in index points. Notional uses your multiplier and is not capital required, margin or a profit estimate.'}</p>
    {r.market_gap!==null&&<Panel title="Entered market quote vs. model"><div className="analytics-audit-summary"><div><span>Market minus model / unit</span><strong>{number(r.market_gap)}</strong></div>{option?<div><span>European implied volatility</span><strong>{r.implied_volatility===null?'Unavailable':number(r.implied_volatility)+'%'}</strong></div>:<div><span>Gap / model price</span><strong>{number(r.market_gap_percent)}%</strong></div>}</div><p className="note">Positive means your entered market quote is above this model estimate. Differences can reflect missing assumptions, conventions or costs.</p></Panel>}
    {option&&r.greeks&&<Panel title="European Greeks"><div className="greek-strip">{Object.entries(r.greeks).map(([k,v])=><div key={k}><span>{greekLabels[k]}</span><strong>{number(v)}</strong><small>{greekUnits[k]}</small></div>)}</div><p className="note">Per option unit, holding other inputs constant. Multiply by units per contract and number of contracts for a long position’s local sensitivity. 1pp means one percentage point (for example 20% → 21%). Greeks are local approximations; use the grid for larger changes. — means unavailable.</p></Panel>}
    {c&&<Panel title="American tree convergence"><div className="table-wrap"><table aria-label="American tree convergence"><thead><tr><th>Check</th><th>Price / unit</th></tr></thead><tbody>{[[`${c.coarse_steps.toLocaleString()} steps`,c.coarse_price],[`${c.fine_steps.toLocaleString()} steps · reported price`,c.fine_price],['Absolute difference between resolutions',c.difference],['European option · same finer tree',c.european_tree],['European option · Black–Scholes–Merton',c.european_closed],['European tree minus closed form',c.european_tree_error],['Early exercise premium · same tree comparison',c.early_exercise_premium]].map(([label,v])=><tr key={label}><th scope="row">{label}</th><td>{number(v)}</td></tr>)}</tbody></table></div><p className="note">The resolution difference is a numerical stability check, not an error bound. Early exercise premium compares American and European values on the same tree. At expiry or zero volatility, analytical limits replace the tree. The grid below fully reprices American exercise; European Greeks are not shown for this model.</p></Panel>}
    <Panel title={option?'Price × volatility sensitivity':'Spot × funding rate sensitivity'}><div className="table-wrap"><table className="sensitivity-table" aria-label="Derivative price sensitivity"><thead><tr><th>Spot ↓ / {option?'volatility':'rate'} % →</th>{r.sensitivity.columns.map(v=><th key={v}>{decimal(v,2)}%</th>)}</tr></thead><tbody>{r.sensitivity.rows.map(row=><tr key={row.spot}><th scope="row">{number(row.spot)}</th>{row.values.map((v,i)=>{const base=row.spot===Number(a.spot)&&r.sensitivity.columns[i]===Number(option?a.volatility:a.rate);return <td key={i} className={base?'pricing-base-cell':''} style={v===null?undefined:{backgroundColor:`rgba(92,178,176,${Math.min(.25,.04+Math.abs(v-r.unit_price)/Math.max(r.unit_price,.01)*.15)})`}}>{number(v)}{base&&<small>Entered case</small>}</td>;})}</tr>)}</tbody></table></div><p className="note">Each cell is a new model price per unit, holding other inputs constant. Spot moves ±10% and ±20%. {option?'Volatility moves ±5 and ±10 percentage points, bounded at 0–300%.':'The funding rate moves ±0.5 and ±1 percentage point.'} Shading shows distance from the entered price estimate, not profit or probability. — means the tree could not price that combination.</p></Panel>
    <details className="model-settings"><summary>Calculation details</summary>{!option&&<p className="note pricing-formula">{r.audit.formula}</p>}<div className="analytics-audit-summary"><div><span>Time in years</span><strong>{number(r.years)}</strong></div>{audit.map(([label,v])=><div key={label}><span>{label}</span><strong>{number(v)}</strong></div>)}</div>{c&&<div className="analytics-audit-summary">{[['Up factor / step',c.up],['Down factor / step',c.down],['Risk-neutral up probability',c.probability],['Discount factor / step',c.discount]].map(([label,v])=><div key={label}><span>{label}</span><strong>{number(v)}</strong></div>)}</div>}<p className="note">Annual rates are continuously compounded. Time = actual calendar days ÷ 365. {option?'d₁ and d₂ belong to the European benchmark.':'Spot sensitivity is the change in delivery price per +1 spot unit; rate sensitivity is per +1 percentage point, locally.'} Displayed values are rounded; downloads retain the calculation’s full output precision.</p></details>
  </div>;
}
