import StrategyTransfer from './StrategyTransfer.jsx';
import React,{useEffect,useRef,useState} from 'react';
import {ArrowRight,LoaderCircle,Plus} from 'lucide-react';
import {api} from './data.js';
import {Panel} from './components.jsx';
import {analyticsPayload,blankPeer,blankYear,yearFields,peerFields} from './analytics-model.js';
import AnalyticsResults from './AnalyticsResults.jsx';

const yearLabels={ebit:'EBIT',tax_rate:'Tax %',depreciation:'D&A',capex:'Capital expenditure',change_nwc:'Change in operating NWC'};
const peerLabels={name:'Peer name',enterprise_value:'Enterprise value',equity_value:'Common equity value',revenue:'Revenue',ebitda:'EBITDA',net_income:'Common net income'};
export default function EquityValuation({inputs:a,onChange,onTransfer,disabled=false}){
  const [section,setSection]=useState('dcf'),[caseName,setCaseName]=useState('Base'),[saved,setSaved]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const payload=analyticsPayload(a),key=JSON.stringify(payload),latest=useRef(key),run=useRef(0),current=useRef(a);
  latest.current=key;current.current=a;
  const result=saved?.key===key?saved.data:null;
  useEffect(()=>()=>{run.current++;},[]);
  useEffect(()=>setError(''),[key]);
  const update=patch=>onChange({...current.current,...patch});
  const field=(name,label,type='number',help='')=><label>{label}<input aria-label={label} type={type} step="any" maxLength={name==='company'?100:undefined} value={a[name]} onChange={e=>update({[name]:e.target.value})}/>{help&&<small className="muted">{help}</small>}</label>;
  const selected=a.cases.find(c=>c.name===caseName);
  const updateCase=patch=>update({cases:a.cases.map(c=>c.name===caseName?{...c,...patch}:c)});
  function changeYears(add){update({cases:a.cases.map(c=>({...c,years:add?[...c.years,blankYear()]:c.years.slice(0,-1)}))});}
  async function calculate(e){e.preventDefault();const id=++run.current;setBusy(true);setSaved(null);setError('');try{const data=await api('/analytics/valuation',payload);if(run.current===id&&latest.current===key)setSaved({key,data});}catch(e){if(run.current===id&&latest.current===key)setError(e.message);}finally{if(run.current===id)setBusy(false);}}
  return <div className="analytics-lab">
    <div className="section-heading"><div><h2>Equity valuation</h2><p>DCF, comparable companies and valuation ranges.</p></div></div>
    <form onSubmit={calculate} noValidate><fieldset disabled={disabled} className="analytics-form">
      <Panel title="Company & hypothesis">
        <div className="options-fields">{field('company','Company / ticker','text')}{field('valuation_date','Valuation date','date')}<label>Currency<select aria-label="Valuation currency" value={a.currency} onChange={e=>update({currency:e.target.value})}>{['USD','CAD','EUR','GBP'].map(c=><option key={c}>{c}</option>)}</select></label><label>Input scale<select aria-label="Input scale" value={a.units} onChange={e=>update({units:e.target.value})}>{['units','thousands','millions','billions'].map(u=><option key={u} value={u}>{u}</option>)}</select></label>{field('shares',`Diluted shares (${a.units})`)}{field('current_price','Current share price (optional)','number','Actual currency per share; never scaled.')}</div>
        <p className="note">Enter all financial amounts and share counts in {a.units} of {a.currency}. For example, with millions selected, enter 100 for 100 million shares. Changing the scale relabels your inputs; it does not convert them. Market price is always per share.</p>
        <div className="analytics-hypothesis"><label>Investment hypothesis<textarea aria-label="Investment hypothesis" rows={3} maxLength={3000} placeholder="What must be true about growth, profitability, reinvestment, and risk? Record sources and dates for your assumptions." value={a.hypothesis} onChange={e=>update({hypothesis:e.target.value})}/></label></div>
        <details className="model-settings" open><summary>Enterprise value → common equity value</summary><div className="options-fields">{field('cash','Excess cash')}{field('nonoperating','Other non-operating assets')}{field('debt','Debt and debt-like claims')}{field('preferred','Preferred equity claims')}{field('minority','Non-controlling interests')}</div><p className="note">Common equity = enterprise value + excess cash + other non-operating assets − debt − preferred claims − non-controlling interests. Zero is an editable assumption. Use values at the valuation date, account for leases consistently, and avoid counting assets or claims twice. P/E values common equity directly.</p></details>
      </Panel>
      <Panel title="Valuation methods">
        <div className="option-tool-row"><label className="inline-check"><input type="checkbox" aria-label="Include DCF" checked={a.dcf_enabled} onChange={e=>update({dcf_enabled:e.target.checked})}/>Include DCF</label><label className="inline-check"><input type="checkbox" aria-label="Include comps" checked={a.comps_enabled} onChange={e=>update({comps_enabled:e.target.checked})}/>Include comps</label></div>
        <div className="option-tool-row"><div className="segmented" role="group" aria-label="Valuation inputs">{[['dcf','DCF forecasts'],['comps','Comparable companies']].map(([id,title])=><button key={id} type="button" aria-pressed={section===id} onClick={()=>setSection(id)}>{title}</button>)}</div></div>
        {section==='dcf'&&<div>
          {!a.dcf_enabled&&<p className="note">DCF inputs are kept, but excluded from the next calculation.</p>}
          <div className="options-fields"><label>Terminal value approach<select aria-label="Terminal value approach" value={a.terminal_method} onChange={e=>update({terminal_method:e.target.value})}><option value="growth">Perpetual growth</option><option value="multiple">Exit EV/EBITDA multiple</option><option value="both">Compare both approaches</option></select></label><label className="inline-check"><input type="checkbox" aria-label="Recognize immediate tax benefits on EBIT losses" checked={a.tax_benefit} onChange={e=>update({tax_benefit:e.target.checked})}/>Recognize immediate tax benefits on EBIT losses</label></div>
          <div className="option-tool-row"><div className="segmented" role="group" aria-label="DCF cases">{a.cases.map(c=><button key={c.name} type="button" aria-pressed={caseName===c.name} onClick={()=>setCaseName(c.name)}>{c.name}{c.enabled?' · included':''}</button>)}</div>{caseName!=='Base'&&<><label className="inline-check"><input type="checkbox" aria-label={`Include ${caseName} case`} checked={selected.enabled} onChange={e=>updateCase({enabled:e.target.checked})}/>Include {caseName} case</label><button type="button" onClick={()=>updateCase({...structuredClone(a.cases.find(c=>c.name==='Base')),name:caseName,enabled:true})}>Copy Base into {caseName}</button></>}</div>
          <p className="note">{caseName} assumptions · {caseName==='Base'?'Base is required when DCF is enabled.':selected.enabled?'Included in valuation range.':'Enable this case to include it in the valuation range.'} Each row represents a full future year after the valuation date. Cash flows and terminal value are discounted at year end.</p>
          <div className="options-fields">{[['wacc','WACC (%)'],...(a.terminal_method!=='multiple'?[['growth','Terminal growth (%)']]:[]),...(a.terminal_method!=='growth'?[['exit_multiple','Exit EV/EBITDA (×)']]:[])].map(([k,label])=><label key={k}>{label}<input type="number" step="any" aria-label={`${caseName} ${label}`} value={selected[k]} onChange={e=>updateCase({[k]:e.target.value})}/></label>)}</div>
          <div className="table-wrap"><table className="analytics-input-table" aria-label={`${caseName} forecasts`}><thead><tr><th>Year</th>{yearFields.map(k=><th key={k}>{yearLabels[k]}</th>)}</tr></thead><tbody>{selected.years.map((y,i)=><tr key={i}><th scope="row">{i+1}</th>{yearFields.map(k=><td key={k}><input aria-label={`${caseName} year ${i+1} ${yearLabels[k]}`} type="number" step="any" value={y[k]} onChange={e=>updateCase({years:selected.years.map((row,j)=>i===j?{...row,[k]:e.target.value}:row)})}/></td>)}</tr>)}</tbody></table></div>
          <div className="option-tool-row"><button type="button" disabled={selected.years.length>=10} onClick={()=>changeYears(true)}><Plus size={15}/>Add forecast year</button><button type="button" disabled={selected.years.length<=1} onClick={()=>changeYears(false)}>Remove last forecast year</button><button type="button" onClick={()=>updateCase({years:selected.years.map(()=>({...selected.years[0]}))})}>Repeat year 1 across {caseName} forecast</button></div>
          <p className="note">FCFF = EBIT − operating tax + depreciation & amortization − capital expenditure − change in operating working capital. Enter positive capex as an outflow; a negative working-capital change releases cash. Enter explicit zeros where appropriate. EBIT excludes interest. Losses receive no tax benefit unless selected; loss carryforwards are not modeled. The final year must reflect sustainable reinvestment before applying terminal growth.</p>
        </div>}
        {section==='comps'&&<div>
          {!a.comps_enabled&&<p className="note">Enable Include comps to use these inputs in the next calculation.</p>}
          <div className="options-fields">{field('period','Shared comparison period / basis','text','For example: FY2027 forward, or LTM as of your valuation date.')}{field('revenue','Target revenue')}{field('ebitda','Target EBITDA')}{field('net_income','Target common net income')}</div>
          <p className="note">Enter at least two eligible peers for each method you want to use. Match reporting periods, currencies, and accounting definitions to the target. Common net income is after preferred dividends. Blank or nonpositive values are excluded for the affected multiple, with the reason shown in results. Entirely blank rows are ignored.</p>
          <div className="table-wrap"><table className="analytics-input-table" aria-label="Comparable company inputs"><thead><tr>{peerFields.map(k=><th key={k}>{peerLabels[k]}</th>)}<th>Remove</th></tr></thead><tbody>{a.peers.map((p,i)=><tr key={i}>{peerFields.map(k=><td key={k}><input aria-label={`Peer ${i+1} ${peerLabels[k]}`} type={k==='name'?'text':'number'} step="any" maxLength={k==='name'?80:undefined} value={p[k]} onChange={e=>update({peers:a.peers.map((row,j)=>i===j?{...row,[k]:e.target.value}:row)})}/></td>)}<td><button aria-label={`Remove peer ${i+1}`} type="button" disabled={a.peers.length===1} onClick={()=>update({peers:a.peers.filter((_,j)=>i!==j)})}>Remove</button></td></tr>)}</tbody></table></div>
          <div className="option-tool-row"><button type="button" disabled={a.peers.length>=30} onClick={()=>update({peers:[...a.peers,blankPeer()]})}><Plus size={15}/>Add peer</button></div>
        </div>}
        <div className="panel-head"><span className="muted small">Save portfolio keeps your assumptions. All valuation inputs come from you.</span><button className="primary" type="submit" disabled={busy||disabled}>{busy?<LoaderCircle size={16} className="spin"/>:<ArrowRight size={16}/>}Calculate valuation</button></div>
      </Panel>
    </fieldset></form>
    {busy&&<p className="banner" role="status">Calculating valuations…</p>}{error&&<p className="banner error" role="alert">{error}</p>}{saved&&!result&&<p className="banner">Assumptions changed. Calculate again to refresh the valuation.</p>}
    {result&&onTransfer&&<StrategyTransfer key={saved.key} type='equity' inputs={a} result={result} onTransfer={onTransfer} disabled={disabled}/>}
    {result&&<AnalyticsResults key={saved.key} result={result} inputs={a}/>}
    <details className="model-settings"><summary>Methodology & model scope</summary><div className="analytics-methodology"><p>This is an enterprise DCF for operating companies. It discounts unlevered cash flows at a constant WACC. Financial institutions generally need a different equity or regulatory-capital framework. Amounts and diluted shares use one consistent scale; all displayed share prices are in actual currency units.</p><p>Perpetual terminal value = final FCFF × (1 + g) ÷ (WACC − g). Exit terminal value = final EBITDA × your EV/EBITDA multiple. Both occur at the final forecast year end. There is no midyear convention, stub period, automatic dilution, loss-carryforward schedule, or automatic reinvestment forecast.</p><p>Comps use eligible peer multiples and linearly interpolated 25th, 50th, and 75th percentiles. Enterprise multiples use the equity bridge; P/E directly values common equity. The football field compares these estimates without combining them into a single target or assigning probabilities. Scenario and peer ranges are not statistical confidence intervals.</p><p>Calculations use decimal arithmetic with 34 significant digits internally; displays round for readability. This is computational precision, not certainty about fair value. Results depend on your forecasts, accounting consistency, and chosen models.</p><p>Method references: <a href="https://pages.stern.nyu.edu/~adamodar/New_Home_Page/lectures/val.html" target="_blank" rel="noreferrer">NYU Stern — DCF</a> · <a href="https://pages.stern.nyu.edu/~adamodar/New_Home_Page/valquestions/termvalapproaches.htm" target="_blank" rel="noreferrer">Terminal value</a> · <a href="https://pages.stern.nyu.edu/~adamodar/New_Home_Page/lectures/multintr.htm" target="_blank" rel="noreferrer">Comparable multiples</a>.</p></div></details>
  </div>;
}
