import React,{useEffect,useRef,useState} from 'react';
import {api,decimal,num} from './data.js';
import {Panel} from './components.jsx';
import {blankLeg,today} from './options-model.js';
const names={long:'Long options',short:'Short options',debit_spread:'Debit spreads',credit_spread:'Credit spreads'};
export default function OptionFinder({inputs,onChange,onSelect,disabled=false}) {
  const [dates,setDates]=useState([]),[saved,setSaved]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const f=inputs.finder,symbol=inputs.symbol.trim().toUpperCase(),key=JSON.stringify([symbol,inputs.spot,inputs.rate,inputs.dividend_yield,inputs.iv_shift,inputs.probability_iv,inputs.fee_per_contract,f]);
  const latest=useRef(key),run=useRef(0);latest.current=key;const result=saved?.key===key?saved.result:null;
  useEffect(()=>()=>{run.current++;},[]);useEffect(()=>{setDates([]);},[symbol]);
  const set=(k,v)=>onChange({...f,[k]:v});
  async function loadDates(){const id=++run.current;setBusy(true);setError('');try{const data=await api('/options/expirations?symbol='+encodeURIComponent(symbol));if(id===run.current&&key===latest.current)setDates(data.expirations);}catch(e){if(id===run.current&&key===latest.current)setError(e.message);}finally{if(id===run.current)setBusy(false);}}
  async function find(e){e.preventDefault();const id=++run.current;setBusy(true);setError('');setSaved(null);try{const result=await api('/options/finder',{symbol,spot:num(inputs.spot),target_date:f.target_date,target_price:num(f.target_price),expirations:f.expirations,types:f.types,option_type:f.option_type,max_risk:num(f.max_risk),min_open_interest:num(f.min_open_interest),pricing:f.pricing,rank:f.rank,rate:num(inputs.rate),dividend_yield:num(inputs.dividend_yield),iv_shift:num(inputs.iv_shift),probability_iv:num(inputs.probability_iv),fee_per_contract:num(inputs.fee_per_contract)});if(id===run.current&&key===latest.current)setSaved({key,result});}catch(e){if(id===run.current&&key===latest.current)setError(e.message);}finally{if(id===run.current)setBusy(false);}}
  const field=(key,label,type='number',placeholder='')=><label>{label}<input aria-label={label} type={type} value={f[key]} placeholder={placeholder} step="any" onChange={e=>set(key,e.target.value)}/></label>;
  function choose(row){onSelect(row.legs.map(l=>({...blankLeg(l.kind,l.side),quantity:String(l.quantity),multiplier:String(l.multiplier),strike:String(l.strike),premium:String(l.premium),expiration:l.expiration,iv:l.iv===null?'':String(l.iv),contract_symbol:l.contract_symbol,quote_note:`Finder ${symbol} · ${f.pricing} · retrieved ${result.fetched_at.join(', ')}`})),{...result,as_of:today()});}
  return <Panel title="Option Finder" action={<span className="eyebrow">Rank by your price scenario</span>}><form onSubmit={find} noValidate>
    <p className="note">Finder rankings exclude borrowing costs. Opening a result starts with borrowing disabled; enable it in the builder to explore funded outcomes. Set the underlying ticker above. Find long or short options and vertical spreads for a target price and date. The rate, yield, IV shift, fees, and probability IV from your scenario also apply here.</p>
    <div className="options-fields">{field('target_price','Finder target price')}{field('target_date','Finder target date','date')}{field('max_risk','Maximum expiration risk (optional)','number','No limit')}{field('min_open_interest','Minimum open interest')}<label>Option type<select aria-label="Finder option type" value={f.option_type} onChange={e=>set('option_type',e.target.value)}><option value="both">Calls and puts</option><option value="call">Calls</option><option value="put">Puts</option></select></label><label>Rank results by<select aria-label="Finder ranking" value={f.rank} onChange={e=>set('rank',e.target.value)}><option value="pnl">Scenario profit / loss</option><option value="return">Return on capital basis</option></select></label><label>Entry prices<select aria-label="Finder entry prices" value={f.pricing} onChange={e=>set('pricing',e.target.value)}><option value="natural">Buy at ask / sell at bid</option><option value="mid">Bid/ask midpoint</option></select></label></div>
    <div className="option-checks">{Object.entries(names).map(([k,name])=><label key={k}><input type="checkbox" checked={f.types.includes(k)} onChange={e=>set('types',e.target.checked?[...f.types,k]:f.types.filter(v=>v!==k))}/>{name}</label>)}</div>
    <div className="option-tool-row"><button type="button" disabled={!symbol||busy||disabled} onClick={loadDates}>Load available expirations</button><span className="muted">Choose up to four expirations on or after the target date.</span></div>
    <div className="expiry-choices">{[...new Set([...dates,...f.expirations])].sort().map(d=><label key={d}><input type="checkbox" checked={f.expirations.includes(d)} disabled={!f.expirations.includes(d)&&f.expirations.length>=4} onChange={e=>set('expirations',e.target.checked?[...f.expirations,d]:f.expirations.filter(v=>v!==d))}/>{d}</label>)}</div>
    <div className="option-tool-row"><button type="submit" className="primary" disabled={!symbol||busy||disabled}>{busy?'Searching…':'Find options'}</button></div>
  </form>{error&&<p className="banner error" role="alert">{error}</p>}{saved&&!result&&<p className="banner">Finder inputs changed. Search again to update the results.</p>}
    {result&&<><p className="note">{result.eligible_results} matching scenarios · {result.examined} evaluated · {result.skipped} excluded for unusable prices or model inputs. Showing the top {result.results.length}. {result.currency}; target {decimal(result.target_price)} on {result.target_date}.</p><div className="table-wrap"><table aria-label="Option Finder results"><thead><tr><th>Strategy</th><th>Expiration / strikes</th><th>Entry debit / credit</th><th>Scenario P&L</th><th>Return</th><th>Maximum loss</th><th>Model PoP at expiry</th><th>Open</th></tr></thead><tbody>{result.results.map((row,i)=><tr key={i}><td>{names[row.type]}</td><td>{row.expiration}<br/>{row.legs.map(l=>`${l.side} ${l.kind} ${l.strike}`).join(' / ')}</td><td>{decimal(Math.abs(row.initial_debit))} {row.initial_debit>=0?'debit':'credit'}</td><td className={row.pnl>=0?'positive':'negative'}>{decimal(row.pnl)}</td><td>{row.return_percent===null?'—':decimal(row.return_percent)+'%'}</td><td>{row.maximum_loss===null?'Unlimited':decimal(row.maximum_loss)}</td><td>{decimal(row.probability_of_profit*100)}%</td><td><button type="button" onClick={()=>choose(row)}>Open strategy</button></td></tr>)}</tbody></table></div>{!result.results.length&&<p className="banner">No contracts match these settings with usable quotes. Try another expiration or adjust the filters.</p>}<p className="note">{result.note}</p></>}
  </Panel>;
}
