import React,{useEffect,useRef,useState} from 'react';
import {FlaskConical,ArrowRight,LoaderCircle,Plus,Trash2,Copy,Save} from 'lucide-react';
import {api,download} from './data.js';
import {Panel} from './components.jsx';
import {strategies,descriptions,blankLeg,templateLegs,modelPayload,setupSnapshot,emptyOptions,validOptions,today} from './options-model.js';
import OptionChain from './OptionChain.jsx';
import OptionFinder from './OptionFinder.jsx';
import OptionsResults from './OptionsResults.jsx';
import OptionsExposure from './OptionsExposure.jsx';

export default function OptionsLab({inputs,onChange,disabled=false}) {
  const [tab,setTab]=useState('strategy'),[saved,setSaved]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [selected,setSelected]=useState(''),[comparisons,setComparisons]=useState(null),[shared,setShared]=useState(null);
  const payload=modelPayload(inputs),key=JSON.stringify(payload),latest=useRef(key),current=useRef(inputs),run=useRef(0);latest.current=key;current.current=inputs;
  const result=saved?.key===key?saved.data:null;
  const calculated=useRef(false),previousMultiple=useRef(inputs.exposure_multiplier);
  useEffect(()=>{const changed=previousMultiple.current!==inputs.exposure_multiplier;previousMultiple.current=inputs.exposure_multiplier;if(changed&&calculated.current&&!disabled)calculate();},[inputs.exposure_multiplier]);
  useEffect(()=>()=>{run.current++;},[]);
  useEffect(()=>{setError('');},[key]);
  useEffect(()=>{if(location.hash.startsWith('#options=')){try{if(location.hash.length>40000)throw Error();const parsed=JSON.parse(decodeURIComponent(location.hash.slice(9)));const candidate={...emptyOptions(),...parsed};if(!validOptions(candidate))throw Error();setShared(setupSnapshot(candidate));}catch{setNotice('This scenario link could not be read. Your existing inputs are unchanged.');}}},[]);
  const update=patch=>onChange({...current.current,...patch});
  const set=(field,value)=>update({[field]:value});
  const legSet=(i,field,value)=>update({legs:current.current.legs.map((l,j)=>j===i?{...l,[field]:value,...(['kind','strike','expiration','multiplier'].includes(field)?{contract_symbol:'',quote_note:''}:{})}:l)});
  const field=(name,label,type='number',placeholder='')=><label>{label}<input aria-label={label} type={type} step="any" value={inputs[name]} placeholder={placeholder} onChange={e=>set(name,e.target.value)}/></label>;
  const optionsCount=inputs.legs.filter(l=>l.kind!=='stock').length;
  function selectStrategy(value){update({strategy:value,legs:templateLegs(value,inputs.option_type),target_date:'',valuation_mode:['calendar','diagonal','double_diagonal','pmcc'].includes(value)?'dated':inputs.valuation_mode});setSaved(null);setNotice('Template loaded. Enter or select each leg’s actual contract details.');}
  function changeSymbol(value){update({symbol:value.toUpperCase()});if(inputs.legs.some(l=>l.contract_symbol))setNotice('Underlying changed. Review existing legs and reload quotes before calculating.');}
  async function calculate(e){e?.preventDefault();calculated.current=true;const id=++run.current;setBusy(true);setError('');setSaved(null);try{const data=await api('/options/model',payload);if(id===run.current&&key===latest.current)setSaved({key,data});}catch(e){if(id===run.current&&key===latest.current)setError(e.message);}finally{if(id===run.current)setBusy(false);}}
  function quote(leg,target,chain){
    const o=current.current;if(chain.symbol!==o.symbol.trim().toUpperCase())return;
    if(target==='new'&&o.legs.filter(l=>l.kind!=='stock').length>=8){setNotice('Eight option legs are already present. Choose a leg to replace in the chain controls.');return;}
    const legs=target==='new'?[...o.legs,leg]:o.legs.map((l,i)=>i===Number(target)?{...leg,quantity:l.quantity}:l);
    update({legs,currency:chain.currency,spot:chain.spot===null?o.spot:String(chain.spot),strategy:target==='new'?'custom':o.strategy});setTab('strategy');setNotice('Contract selected. Check its premium, quantity, and size before calculating.');
  }
  function keepScenario(){const o=current.current,name=o.scenario_name.trim()||`${strategies[o.strategy]} ${o.symbol}`.trim();const existing=o.scenarios.find(s=>s.name.toLowerCase()===name.toLowerCase());if(!existing&&o.scenarios.length>=12){setNotice('This workspace already holds 12 scenarios. Rename to update an existing scenario or remove one first.');return;}const snapshot={id:existing?.id||crypto.randomUUID(),name,state:setupSnapshot(o)};update({scenarios:existing?o.scenarios.map(s=>s.id===existing.id?snapshot:s):[...o.scenarios,snapshot]});setSelected(snapshot.id);setComparisons(null);setNotice('Scenario kept in this workspace. Save portfolio also saves these scenarios to the device.');}
  function loadScenario(){const s=inputs.scenarios.find(s=>s.id===selected);if(s){update({...setupSnapshot(emptyOptions()),...s.state,scenario_name:s.name});setNotice('Scenario loaded. Calculate to refresh its results.');setTab('strategy');}}
  async function compare(){const id=++run.current;setBusy(true);setError('');setComparisons(null);const docs=inputs.scenarios.slice(0,6),stamp=JSON.stringify(docs);try{const rows=await Promise.all(docs.map(async s=>{try{return {name:s.name,result:await api('/options/model',modelPayload({...emptyOptions(),...s.state}))};}catch(e){return {name:s.name,error:e.message};}}));if(id===run.current&&stamp===JSON.stringify(current.current.scenarios.slice(0,6)))setComparisons({stamp,rows});}finally{if(id===run.current)setBusy(false);}}
  async function share(){const link=`${location.origin}${location.pathname}#options=${encodeURIComponent(JSON.stringify(setupSnapshot(inputs)))}`;try{await navigator.clipboard.writeText(link);setNotice('Scenario link copied. It opens in a running local Portfolio Tracker; it is not a public hosted page.');}catch{download({name:'options-scenario-link.txt',mime:'text/plain',content:link});setNotice('Scenario link downloaded. It requires a running local Portfolio Tracker.');}}
  return <div className="options-lab">
    <div className="section-heading"><div><h1>Options Lab</h1><p>Build a position. Explore price, time, and volatility.</p></div><span className="eyebrow">Delayed quotes · model estimates</span></div>
    {notice&&<p className="banner" role="status">{notice}</p>}
    {shared&&<div className="banner"><span>This link contains an options scenario.</span><button type="button" onClick={()=>{update(shared);setShared(null);history.replaceState(null,'',location.pathname+location.search);setNotice('Shared scenario loaded into the current workspace.');}}>Load linked scenario</button><button type="button" onClick={()=>{setShared(null);history.replaceState(null,'',location.pathname+location.search);}}>Dismiss</button></div>}
    <Panel title="Underlying & workspace" action={<FlaskConical size={18}/>}><div className="options-fields"><label>Underlying ticker<input aria-label="Options underlying ticker" value={inputs.symbol} maxLength={40} placeholder="AAPL, SPY, or Canadian ticker" onChange={e=>changeSymbol(e.target.value)}/></label>{field('spot','Current underlying price')}<label>Currency<select aria-label="Options currency" value={inputs.currency} onChange={e=>set('currency',e.target.value)}><option value="USD">USD</option><option value="CAD">CAD</option></select></label></div><div className="option-tool-row options-subtabs" role="group" aria-label="Options tools">{[['strategy','Strategy builder'],['chain','Option chain'],['finder','Option Finder']].map(([id,label])=><button type="button" key={id} aria-pressed={tab===id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div></Panel>
    {tab==='chain'&&<OptionChain inputs={inputs} onQuote={quote} onUnderlying={data=>{if(data.symbol===current.current.symbol.trim().toUpperCase())update({currency:data.currency,spot:data.spot===null?current.current.spot:String(data.spot)});}} disabled={disabled}/>}
    {tab==='finder'&&<OptionFinder inputs={inputs} onChange={finder=>update({finder})} onSelect={(legs,data)=>{update({legs,spot:String(data.spot),currency:data.currency,as_of:data.as_of,target_date:data.target_date,scenario_price:String(data.target_price),strategy:'custom',valuation_mode:'dated',financing_enabled:false,exposure_multiplier:'1'});setTab('strategy');setNotice('Finder position loaded. Calculate to explore its full price and date scenarios.');}} disabled={disabled}/>}
    {tab==='strategy'&&<form onSubmit={calculate} noValidate><Panel title="Strategy builder">
      <div className="options-fields"><label>Strategy template<select aria-label="Options strategy" value={inputs.strategy} onChange={e=>selectStrategy(e.target.value)}>{Object.entries(strategies).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label>Calculation mode<select aria-label="Options calculation mode" value={inputs.valuation_mode} onChange={e=>set('valuation_mode',e.target.value)}><option value="dated">Dates & time value</option><option value="expiry">Expiration payoff only</option></select></label>{field('scenario_price','Scenario underlying price','number','Defaults to current price / first strike')}</div><p className="note">{descriptions[inputs.strategy]} Templates are starting structures; the calculation always uses the legs you enter below.</p>
      <OptionsExposure inputs={inputs} result={result} busy={busy} onChange={value=>set('exposure_multiplier',value)} disabled={disabled}/>
      <div className="option-leg-list">{inputs.legs.map((leg,i)=><fieldset className="option-leg-card" key={i}><legend>Leg {i+1} · {leg.side==='buy'?'Long':'Short'} {leg.kind==='stock'?'shares':leg.kind}</legend><div className="leg-top"><label>Buy / sell<select aria-label={`Leg ${i+1} side`} value={leg.side} onChange={e=>legSet(i,'side',e.target.value)}><option value="buy">Buy / long</option><option value="sell">Sell / short</option></select></label><label>Instrument<select aria-label={`Leg ${i+1} type`} value={leg.kind} onChange={e=>legSet(i,'kind',e.target.value)}><option value="call">Call</option><option value="put">Put</option><option value="stock">Stock</option></select></label><button className="icon-button" type="button" aria-label={`Remove leg ${i+1}`} disabled={inputs.legs.length<=1||disabled} onClick={()=>update({legs:inputs.legs.filter((_,j)=>i!==j)})}><Trash2 size={16}/></button></div><div className="leg-fields">{(leg.kind==='stock'?[['quantity','Shares'],['premium','Entry price per share']]:[['quantity','Contracts'],['multiplier','Contract size'],['strike','Strike'],['premium','Premium per unit'],['expiration','Expiration'],['iv','IV % (blank = infer)']]).map(([k,label])=><label key={k}>{label}<input aria-label={`Leg ${i+1} ${label}`} type={k==='expiration'?'date':'number'} min="0" step={k==='quantity'&&leg.kind!=='stock'||k==='multiplier'?'1':'any'} value={leg[k]} placeholder={k==='iv'?'Auto from premium':''} onChange={e=>legSet(i,k,e.target.value)}/></label>)}</div>{leg.quote_note&&<p className="note">{leg.contract_symbol&&<strong>{leg.contract_symbol} · </strong>}{leg.quote_note}</p>}</fieldset>)}</div>
      <div className="option-tool-row"><button type="button" disabled={optionsCount>=8||disabled} onClick={()=>update({legs:[...inputs.legs,blankLeg()],strategy:'custom'})}><Plus size={16}/>Add option leg</button><button type="button" disabled={inputs.legs.some(l=>l.kind==='stock')||disabled} onClick={()=>update({legs:[...inputs.legs,{...blankLeg('stock'),quantity:'100',multiplier:'1'}],strategy:'custom'})}>Add stock position</button><button type="button" onClick={()=>setTab('chain')}>Choose contracts from chain</button><span className="muted">{optionsCount}/8 option legs</span></div>
      <details className="model-settings" open><summary>Model settings</summary><div className="options-fields">{inputs.valuation_mode==='dated'&&<>{field('as_of','Calculation date','date')}{field('target_date','Scenario date','date')}{field('rate','Annual risk-free rate (%)')}{field('dividend_yield','Annual dividend yield (%)')}{field('iv_shift','IV shift (percentage points)')}{field('probability_iv','Probability model IV (%)')}</>}{field('range_min','Chart minimum price','number','Automatic')}{field('range_max','Chart maximum price','number','Automatic')}{field('fee_per_contract','Round-trip fee per option contract')}{!inputs.financing_enabled&&field('capital_basis','Return capital basis (optional)','number','Automatic')}{field('comparison_budget','Stock comparison budget (optional)','number','Uses capital basis')}</div><label className="inline-check"><input type="checkbox" disabled={inputs.financing_enabled} checked={inputs.financing_enabled||inputs.include_stock_cost} onChange={e=>set('include_stock_cost',e.target.checked)}/>Include stock cost in the automatic return basis</label><p className="note">Rates and fees default to zero assumptions. IV is annualized; a +5 shift means 25% becomes 30%. Blank leg IV is inferred from its entry premium. Scenario dates stop at the earliest expiry. All legs must reference the same underlying and currency. Leg quantities are your 1× base. Any manually entered return capital or stock comparison budget stays fixed when exposure changes.</p></details>
      <details className="model-settings" open={inputs.financing_enabled}><summary>Borrowing (optional)</summary>
        <p className="note">Borrowing funds part of the total position. The loan amount stays fixed when you change the exposure multiplier.</p>
        <label className="inline-check"><input aria-label="Include borrowing costs" type="checkbox" checked={inputs.financing_enabled} onChange={e=>set('financing_enabled',e.target.checked)}/>Include borrowing costs (optional)</label>
        {inputs.financing_enabled&&<><div className="options-fields">{field('borrowed_amount','Borrowed toward entry debit')}{field('borrowing_rate','Annual borrowing rate (%)')}{inputs.valuation_mode==='expiry'&&field('financing_days','Holding days for borrowing')}</div><p className="note">Own capital = full net entry debit minus the loan. The loan must be smaller than a positive entry debit. Simple interest accrues on a constant balance using actual days / 365, from the calculation date in date-based mode. This replaces the return denominator with own capital. Broker eligibility, collateral rules, margin calls, compounding, and stock-borrow fees are not modeled.</p></>}
      </details>
      <div className="panel-head"><span className="muted small">Premiums are per unit. Quantity × contract size scales option value.</span><button className="primary" type="submit" disabled={busy||disabled}>{busy?<LoaderCircle className="spin" size={16}/>:<ArrowRight size={16}/>}Calculate strategy</button></div>
    </Panel></form>}
    {busy&&<p className="banner" role="status">Calculating scenarios…</p>}{error&&<p className="banner error" role="alert">{error}</p>}{saved&&!result&&<p className="banner">Options inputs changed. Calculate again to update results.</p>}
    {result&&tab==='strategy'&&<OptionsResults key={saved.key} result={result} inputs={inputs} onChange={set}/>}
    <Panel title="Keep, compare & share scenarios"><div className="option-tool-row"><label>Scenario name<input aria-label="Options scenario name" value={inputs.scenario_name} maxLength={80} placeholder="e.g. AAPL call spread" onChange={e=>set('scenario_name',e.target.value)}/></label><button type="button" disabled={disabled} onClick={keepScenario}><Save size={16}/>Keep scenario</button><button type="button" onClick={share}><Copy size={16}/>Copy scenario link</button></div><div className="option-tool-row"><label>Kept scenarios<select aria-label="Kept options scenarios" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select a scenario</option>{inputs.scenarios.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button type="button" disabled={!selected||disabled} onClick={loadScenario}>Load scenario</button><button type="button" disabled={!selected||disabled} onClick={()=>{update({scenarios:inputs.scenarios.filter(s=>s.id!==selected)});setSelected('');setComparisons(null);}}>Remove kept scenario</button><button type="button" disabled={!inputs.scenarios.length||busy||disabled} onClick={compare}>Compare kept scenarios</button></div><p className="note">Keep up to 12 scenarios within this portfolio. Save portfolio stores them on your device. Comparison recalculates the first six using each scenario’s own prices, dates, and currency; it does not normalize their risk. Scenario links contain only option inputs and require a running local tracker.</p>
      {comparisons?.stamp===JSON.stringify(inputs.scenarios.slice(0,6))&&<div className="table-wrap"><table aria-label="Kept scenario comparison"><thead><tr><th>Scenario</th><th>Underlying / currency</th><th>Target date / price</th><th>Exposure</th><th>Initial debit</th><th>Scenario P&L</th><th>Return</th><th>Max expiration loss</th><th>Effective leverage</th><th>Interest at target</th></tr></thead><tbody>{comparisons.rows.map((r,i)=><tr key={i}><td>{r.name}</td>{r.error?<td colSpan={9}>{r.error}</td>:<><td>{r.result.symbol||'Manual'} / {r.result.currency}</td><td>{r.result.target_date} / {r.result.scenario_price.toFixed(2)}</td><td>{inputs.scenarios[i].state.exposure_multiplier??'1'}×</td><td>{r.result.initial_debit.toFixed(2)}</td><td>{r.result.scenario_pnl.toFixed(2)}</td><td>{r.result.scenario_return_percent===null?'—':r.result.scenario_return_percent.toFixed(2)+'%'}</td><td>{!r.result.summary?'Not defined':r.result.summary.loss_unlimited?'Unlimited':r.result.summary.maximum_loss.toFixed(2)}</td><td>{r.result.leverage?.effective_leverage==null?'—':r.result.leverage.effective_leverage.toFixed(2)+'×'}</td><td>{(r.result.financing?.scenario_interest??0).toFixed(2)}</td></>}</tr>)}</tbody></table></div>}
    </Panel><p className="note">Quotes may be delayed or unavailable. Option values and Greeks are model estimates, not executable prices. These scenarios do not place orders or alter your equity holdings. <a href="https://www.optionsprofitcalculator.com/faq.html" target="_blank" rel="noreferrer">Feature reference</a> · <a href="https://www.soa.org/globalassets/assets/Files/Edu/2018/exam-ifm-cbt-table.pdf" target="_blank" rel="noreferrer">Model Greeks reference</a></p>
  </div>;
}
