import React,{useState,useRef} from 'react';
import {CartesianGrid,Line,LineChart,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {decimal,download} from './data.js';
import {Metric,Panel} from './components.jsx';
import OptionsLeverage from './OptionsLeverage.jsx';
const labels={pnl:'Profit / loss',return_percent:'Return on capital basis',position_value:'Net position value'};
const colors=['#e9b66c','#5dc9b0','#759be8'];
export default function OptionsResults({result,inputs,onChange}) {
  const [cell,setCell]=useState(null),chartNode=useRef(null),s=result.summary,output=inputs.output;
  const money=v=>Number.isFinite(v)?new Intl.NumberFormat('en-US',{style:'currency',currency:result.currency,maximumFractionDigits:2}).format(v):'—';
  const fmt=v=>output==='return_percent'?(v===null?'—':decimal(v)+'%'):money(v);
  const be=s?[...s.break_evens.map(money),...s.break_even_ranges.map(r=>r.to===null?`${money(r.from)} and above`:`${money(r.from)}–${money(r.to)}`)].join(' · ')||'None':'Depends on settlement';
  const chart=result.chart.map(r=>({...r,selected:r[output],start:output==='pnl'?r.start_pnl:output==='position_value'?(r.start_position_value??r.start_pnl+result.initial_debit):result.capital_basis?r.start_pnl/result.capital_basis*100:null,end:output==='pnl'?r.horizon_pnl:output==='position_value'?(r.horizon_position_value??r.horizon_pnl+result.initial_debit):result.capital_basis?r.horizon_pnl/result.capital_basis*100:null}));
  const scale=Math.max(1,...result.grid.flatMap(r=>r.values.map(c=>Math.abs(c[output]||0))));
  function exportCsv(){const rows=[['Underlying','Currency','Underlying price','Date','P&L','Return on capital basis (%)','Net position value','Capital basis','Fees','Loan principal','Interest cost','Equity after loan repayment','Effective leverage at calculation date','Leverage capital basis','Exposure multiplier']];for(const r of result.grid)for(const c of r.values)rows.push([result.symbol,result.currency,r.price,c.date,c.pnl,c.return_percent,c.position_value,result.capital_basis,result.fees,result.financing?.principal??0,c.interest_cost??0,c.equity_value??null,result.leverage?.effective_leverage??null,result.leverage?.capital??null,inputs.exposure_multiplier??'1']);const escape=v=>'"'+(typeof v==='string'&&/^[=+@-]/.test(v)?"'":'')+String(v??'').replaceAll('"','""')+'"';download({name:'options-scenarios.csv',mime:'text/csv',content:rows.map(r=>r.map(escape).join(',')).join('\n')});}
  function exportChart(){const svg=chartNode.current?.querySelector('svg.recharts-surface');if(!svg)return;const copy=svg.cloneNode(true);copy.setAttribute('xmlns','http://www.w3.org/2000/svg');copy.setAttribute('style','background:#111923;color:#dce5f1');download({name:'options-payoff.svg',mime:'image/svg+xml',content:new XMLSerializer().serializeToString(copy)});}
  return <div className="options-results">
    <div className="section-heading"><div><h2>Scenario results{result.symbol?' · '+result.symbol:''}</h2><p>{inputs.exposure_multiplier??'1'}× exposure · {result.currency} · {result.mode==='dated'?`Scenario ${result.target_date} · first expiry ${result.horizon}`:'At expiration'}</p></div><button type="button" onClick={exportCsv}>Download scenario CSV</button></div>
    {result.warnings.map(w=><p key={w} className="banner">{w}</p>)}
    <div className="metrics"><Metric label="Maximum profit at expiry" value={!s?'Not defined':s.profit_unlimited?'Unlimited':money(s.maximum_profit)} note="Full price range; independent of chart zoom"/><Metric label="Maximum loss at expiry" value={!s?'Not defined':s.loss_unlimited?'Unlimited':money(s.maximum_loss)} note="Includes premiums, fees, and enabled borrowing costs"/><Metric label="Break-even at expiry" value={be} note="Underlying price; same-expiry positions"/><Metric label="Scenario P&L" value={money(result.scenario_pnl)} tone={result.scenario_pnl>=0?'positive':'negative'} note={`Underlying ${money(result.scenario_price)} · ${result.target_date}`}/></div>
    <div className="options-summary"><div><span>Net initial {result.initial_debit>=0?'debit':'credit'}</span><strong>{money(Math.abs(result.initial_debit))}</strong></div><div><span>{result.basis_label}</span><strong>{money(result.capital_basis)}</strong></div><div><span>Scenario return on basis</span><strong>{result.scenario_return_percent===null?'—':decimal(result.scenario_return_percent)+'%'}</strong></div><div><span>Model probability of ≥ 0 P&L at expiry</span><strong>{result.probability_of_profit===null?'Unavailable':decimal(result.probability_of_profit*100)+'%'}</strong></div></div>
    <details className="model-settings"><summary>Advanced sensitivity & borrowing details</summary><OptionsLeverage result={result} money={money}/></details>
    <Panel title="Explore price and time" action={<span className="eyebrow">{labels[output]}</span>}>
      <div className="option-tool-row"><div className="segmented" role="group" aria-label="Results view">{[['heatmap','Heatmap'],['line','Line chart'],['table','Values table']].map(([v,label])=><button type="button" aria-pressed={inputs.result_view===v} key={v} className={inputs.result_view===v?'active':''} onClick={()=>onChange('result_view',v)}>{label}</button>)}</div><label>Output values<select aria-label="Output values" value={output} onChange={e=>onChange('output',e.target.value)}>{Object.entries(labels).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label></div>
      {output==='return_percent'&&result.capital_basis===null&&<p className="banner">Percentage returns need a positive capital basis. Enter one in Model settings and recalculate.</p>}
      {inputs.result_view!=='line'?<><div className="table-wrap payoff-grid"><table aria-label="Options price and date scenarios"><thead><tr><th>Underlying price ↓ / date →</th>{result.dates.map(d=><th key={d}>{d}{d===result.horizon?<small>First / only expiry</small>:null}</th>)}</tr></thead><tbody>{result.grid.map(row=><tr key={row.price}><th scope="row">{money(row.price)}</th>{row.values.map(c=><td key={c.date}><button type="button" style={inputs.result_view==='heatmap'&&c[output]!==null?{background:c[output]>=0?`rgba(43,164,137,${.12+.58*Math.sqrt(Math.abs(c[output])/scale)})`:`rgba(205,75,93,${.12+.58*Math.sqrt(Math.abs(c[output])/scale)})`}:undefined} aria-label={`${money(row.price)} on ${c.date}: ${labels[output]} ${fmt(c[output])}`} onClick={()=>setCell({...c,price:row.price})}>{fmt(c[output])}</button></td>)}</tr>)}</tbody></table></div>{cell&&<p className="banner" role="status">At {money(cell.price)} on {cell.date}: P&L {money(cell.pnl)} · return {cell.return_percent===null?'unavailable':decimal(cell.return_percent)+'%'} · net position value {money(cell.position_value)}{result.financing?.enabled&&<> · interest {money(cell.interest_cost)} · equity after loan repayment {money(cell.equity_value)}</>}.</p>}</>:<div ref={chartNode}>
        <div className="legend"><span><i style={{background:colors[0]}}/>Selected scenario date</span>{result.mode==='dated'&&<><span><i style={{background:colors[1]}}/>Calculation date</span><span><i style={{background:colors[2]}}/>First expiry</span></>}</div>
        <div className="chart" role="group" aria-label="Options payoff line chart"><ResponsiveContainer width="100%" height="100%" minWidth={0}><LineChart data={chart} margin={{top:20,right:22,bottom:28,left:18}} accessibilityLayer><CartesianGrid stroke="#283340" vertical={false} strokeDasharray="3 3"/><XAxis dataKey="price" type="number" domain={[result.range_min,result.range_max]} stroke="#a0aec0" tick={{fontSize:12}} tickFormatter={v=>decimal(v,0)} label={{value:`Underlying price (${result.currency})`,position:'bottom',offset:5,fill:'#a0aec0',fontSize:12}}/><YAxis width={76} stroke="#a0aec0" tick={{fontSize:12}} tickFormatter={v=>Math.abs(v)>=1000?decimal(v/1000,1)+'k':decimal(v,0)}/><ReferenceLine y={0} stroke="#8095ad" strokeDasharray="4 4"/>{(s?.break_evens||[]).filter(v=>v>=result.range_min&&v<=result.range_max).map(v=><ReferenceLine key={v} x={v} stroke="#538e84" strokeDasharray="3 4"/>)}<Tooltip contentStyle={{background:'#151e2a',border:'1px solid #3a4a5d',color:'#e8edf4'}} labelFormatter={v=>'Underlying '+money(v)} formatter={v=>fmt(v)}/><Line name="Scenario date" dataKey="selected" type="linear" stroke={colors[0]} strokeWidth={2.5} dot={false} isAnimationActive={false}/>{result.mode==='dated'&&<><Line name="Calculation date" dataKey="start" type="linear" stroke={colors[1]} strokeWidth={1.5} dot={false} isAnimationActive={false}/><Line name="First expiry" dataKey="end" type="linear" stroke={colors[2]} strokeDasharray="5 4" strokeWidth={1.5} dot={false} isAnimationActive={false}/></>}{inputs.show_stock&&output==='pnl'&&result.comparison_budget&&<Line name="Stock purchase comparison" dataKey="stock_pnl" type="linear" stroke="#d399db" strokeDasharray="3 3" dot={false} isAnimationActive={false}/>}</LineChart></ResponsiveContainer></div><div className="option-tool-row"><label className="inline-check"><input type="checkbox" checked={inputs.show_stock} onChange={e=>onChange('show_stock',e.target.checked)}/>Show stock purchase comparison (P&L)</label><button type="button" onClick={exportChart}>Download chart SVG</button></div>{inputs.show_stock&&<p className="note">{result.comparison_budget?`Stock comparison invests ${money(result.comparison_budget)} at the entered current price; fractional shares, no fees or dividend cash flows.`:'Enter the current stock price and a positive comparison budget to compare stock P&L.'}</p>}
      </div>}
      <p className="note">Dates represent expiration-close snapshots using calendar days / 365. The final column is the first option expiration; later legs retain model time value. Hover or select a table cell for its exact values. Net position value is the signed liquidation value of all legs, before subtracting the initial debit or loan costs. P&L and returns include borrowing interest when enabled.</p>
    </Panel>
    <Panel title="Greeks at calculation date"><div className="greek-strip">{[['delta','Delta','Value change per 1-unit stock move'],['gamma','Gamma','Delta change per 1-unit stock move'],['theta','Theta','Value change per calendar day'],['vega','Vega','Value change per 1 percentage-point IV'],['rho','Rho','Value change per 1 percentage-point rate']].map(([k,name,note])=><div key={k}><span>{name}</span><strong>{decimal(result.greeks[k],k==='gamma'?4:2)}</strong><small>{note}</small></div>)}</div><p className="note">Signed instrument exposure for the whole position at the entered current price, after the IV shift. Theta excludes the separate borrowing interest charge. Greeks are unavailable at expiration or zero volatility. Probability uses a risk-neutral lognormal model with {decimal(result.probability_iv)}% annual volatility; it is not a forecast of trading success.</p></Panel>
    <Panel title="Leg breakdown"><div className="table-wrap"><table aria-label="Options leg breakdown"><thead><tr><th>Leg</th><th>Quantity × size</th><th>Strike / expiry</th><th>Entry per unit</th><th>Effective IV</th><th>Initial cash flow</th><th>Scenario value</th><th>Scenario P&L</th></tr></thead><tbody>{result.legs.map((l,i)=><tr key={i}><td>{l.side} {l.kind}</td><td>{decimal(l.quantity,2)}{l.kind!=='stock'?' × '+l.multiplier:''}</td><td>{l.kind==='stock'?'—':`${money(l.strike)} / ${l.expiration||'expiry'}`}</td><td>{money(l.premium)}</td><td title={l.iv_source||''}>{l.effective_iv===null?'—':decimal(l.effective_iv)+'%'}</td><td>{money(l.initial_cash_flow)}</td><td>{money(l.position_value)}</td><td className={l.pnl>=0?'positive':'negative'}>{money(l.pnl)}</td></tr>)}</tbody></table></div><p className="note">Positive cash flow means money received; negative position value is a liability. Fees total {money(result.fees)} and are charged once to each option contract as the entered round-trip allowance. {result.financing?.enabled&&`Leg P&Ls are before borrowing interest; subtract ${money(result.financing.scenario_interest)} to reconcile to the net scenario P&L. `}{s&&`Best possible expiration P&L: ${s.profit_unlimited?'unlimited':money(s.best_case_pnl)}; worst: ${s.loss_unlimited?'unlimited loss':money(s.worst_case_pnl)}.`}</p></Panel>
  </div>;
}
