import {num} from './data.js';
export const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
export const strategies={long_call:'Long call',long_put:'Long put',covered_call:'Covered call',cash_secured_put:'Cash-secured put',short_call:'Naked call',short_put:'Naked put',protective_put:'Protective put',vertical:'Vertical spread',call_spread:'Call spread',put_spread:'Put spread',credit_spread:'Credit spread',pmcc:"Poor man’s covered call",calendar:'Calendar spread',ratio_backspread:'Ratio backspread',iron_condor:'Iron condor',butterfly:'Butterfly',collar:'Collar',diagonal:'Diagonal spread',double_diagonal:'Double diagonal',straddle:'Straddle',strangle:'Strangle',covered_strangle:'Covered strangle',synthetic_put:'Synthetic put',reverse_conversion:'Reverse conversion',custom:'Custom strategy'};
export const descriptions={long_call:'Buy a call for upside exposure.',long_put:'Buy a put for downside exposure.',covered_call:'Long shares and a short call. Match the share quantity to the call’s deliverable.',cash_secured_put:'Sell a put with cash available to buy the shares at the strike. Collateral is shown as the return basis.',short_call:'Sell a call without covering shares. Potential loss is unlimited.',short_put:'Sell a put. Cash and broker margin requirements are different from the modeled loss.',protective_put:'Long shares protected by a long put.',vertical:'One long and one short option of the same type and expiration, at different strikes.',call_spread:'Buy and sell calls at different strikes with the same expiration.',put_spread:'Buy and sell puts at different strikes with the same expiration.',credit_spread:'Short the higher-premium option and buy protection at another strike.',pmcc:'Buy a longer-dated, lower-strike call and sell a shorter-dated, higher-strike call.',calendar:'Buy the later expiration and sell the earlier expiration at the same strike.',ratio_backspread:'Sell one option and buy two further out-of-the-money options.',iron_condor:'In strike order: long put, short put, short call, long call. Use a common expiration.',butterfly:'Long one low-strike option, short two middle-strike options, long one high-strike option.',collar:'Long shares, a protective put, and a short call.',diagonal:'Buy a later-dated option and sell an earlier-dated option at a different strike.',double_diagonal:'A put diagonal and a call diagonal. Long legs expire later than short legs.',straddle:'Buy a call and a put at the same strike and expiration.',strangle:'Buy a lower-strike put and a higher-strike call with the same expiration.',covered_strangle:'Long shares, a short call, and a short put. Additional cash may be needed for put assignment.',synthetic_put:'Short shares plus a long call, with matching units.',reverse_conversion:'Short shares, buy a call, and sell a put at the same strike and expiration.',custom:'Build up to eight option legs and one stock position. Each leg has its own quantity, size, expiration, and volatility.'};
export const blankLeg=(kind='call',side='buy',quantity='1')=>({kind,side,quantity,multiplier:'100',strike:'',premium:'',expiration:'',iv:'',contract_symbol:'',quote_note:''});
export function templateLegs(strategy,kind='call') {
  const b=(type=kind,q='1')=>blankLeg(type,'buy',q),s=(type=kind,q='1')=>blankLeg(type,'sell',q),stock=(side='buy')=>({...blankLeg('stock',side,'100'),multiplier:'1'});
  return ({long_call:()=>[b('call')],long_put:()=>[b('put')],short_call:()=>[s('call')],short_put:()=>[s('put')],cash_secured_put:()=>[s('put')],covered_call:()=>[stock(),s('call')],protective_put:()=>[stock(),b('put')],vertical:()=>[b(),s()],call_spread:()=>[b('call'),s('call')],put_spread:()=>[b('put'),s('put')],credit_spread:()=>[s('put'),b('put')],pmcc:()=>[b('call'),s('call')],calendar:()=>[b(),s()],diagonal:()=>[b(),s()],ratio_backspread:()=>[s(),b(kind,'2')],iron_condor:()=>[b('put'),s('put'),s('call'),b('call')],butterfly:()=>[b(),s(kind,'2'),b()],collar:()=>[stock(),b('put'),s('call')],double_diagonal:()=>[b('put'),s('put'),s('call'),b('call')],straddle:()=>[b('call'),b('put')],strangle:()=>[b('put'),b('call')],covered_strangle:()=>[stock(),s('call'),s('put')],synthetic_put:()=>[stock('sell'),b('call')],reverse_conversion:()=>[stock('sell'),b('call'),s('put')],custom:()=>[b(),s()]})[strategy]();
}
const legacy=()=>({strategy:'long_call',symbol:'',expiration:'',contracts:'1',multiplier:'100',strike:'',premium:'',stock_entry:'',option_type:'call',long_strike:'',long_premium:'',short_strike:'',short_premium:'',range_min:'0',range_max:'',scenario_price:''});
const advanced=()=>({engine_version:4,exposure_multiplier:'1',valuation_mode:'dated',currency:'USD',spot:'',as_of:today(),target_date:'',rate:'0',dividend_yield:'0',iv_shift:'0',probability_iv:'30',fee_per_contract:'0',capital_basis:'',comparison_budget:'',financing_enabled:false,borrowed_amount:'0',borrowing_rate:'0',financing_days:'',include_stock_cost:true,show_stock:false,output:'pnl',result_view:'heatmap',scenario_name:'',legs:templateLegs('long_call'),scenarios:[],finder:{target_price:'',target_date:'',max_risk:'',min_open_interest:'0',pricing:'natural',rank:'pnl',option_type:'both',types:['long'],expirations:[]}});
export const emptyOptions=()=>({...legacy(),...advanced(),range_min:''});
export function upgradeOptions(value) {
  if(!value)return emptyOptions();
  if([2,3,4].includes(value.engine_version))return {...emptyOptions(),...value,engine_version:4,finder:{...advanced().finder,...value.finder}};
  const old={...legacy(),...value},legs=templateLegs(old.strategy);
  for(const leg of legs){
    leg.quantity=leg.kind==='stock'?String(Number(old.contracts)*Number(old.multiplier)):old.contracts;
    leg.multiplier=leg.kind==='stock'?'1':old.multiplier;leg.expiration=old.expiration;
    leg.strike=old.strategy==='vertical'?(leg.side==='buy'?old.long_strike:old.short_strike):old.strike;
    leg.premium=leg.kind==='stock'?old.stock_entry:old.strategy==='vertical'?(leg.side==='buy'?old.long_premium:old.short_premium):old.premium;
    if(old.strategy==='vertical')leg.kind=old.option_type;
  }
  return {...emptyOptions(),...old,engine_version:4,valuation_mode:'expiry',legs};
}
export function validOptions(value) {
  if(!value||typeof value!=='object'||!Object.hasOwn(strategies,value.strategy))return false;
  if(value.engine_version!==undefined&&![1,2,3,4].includes(value.engine_version))return false;
  if(value.engine_version===4&&!['1','2','3','5'].includes(value.exposure_multiplier))return false;
  if(![2,3,4].includes(value.engine_version))return Object.keys(legacy()).every(k=>typeof value[k]==='string');
  const strings=['symbol','spot','as_of','target_date','rate','dividend_yield','iv_shift','probability_iv','fee_per_contract','capital_basis','comparison_budget','scenario_name','range_min','range_max','scenario_price'];
  if(value.engine_version>=3&&(typeof value.financing_enabled!=='boolean'||!['borrowed_amount','borrowing_rate','financing_days'].every(k=>typeof value[k]==='string'&&value[k].length<=100)))return false;
  return strings.every(k=>typeof value[k]==='string'&&value[k].length<=100)&&['USD','CAD'].includes(value.currency)&&['expiry','dated'].includes(value.valuation_mode)&&['pnl','return_percent','position_value'].includes(value.output)&&['heatmap','line','table'].includes(value.result_view)&&['include_stock_cost','show_stock'].every(k=>typeof value[k]==='boolean')&&Array.isArray(value.legs)&&value.legs.length<=9&&value.legs.every(l=>l&&['call','put','stock'].includes(l.kind)&&['buy','sell'].includes(l.side)&&['quantity','multiplier','strike','premium','expiration','iv'].every(k=>typeof l[k]==='string'&&l[k].length<=100))&&Array.isArray(value.scenarios)&&value.scenarios.length<=12&&value.scenarios.every(s=>s&&typeof s.id==='string'&&typeof s.name==='string'&&s.state&&validOptions({...emptyOptions(),...s.state,scenarios:[]}));
}
export const exposureMultiple=o=>Number(o.exposure_multiplier??'1');
export function scaledQuantity(leg,multiple){
  const quantity=num(leg.quantity);
  return Number.isFinite(quantity)&&quantity>0&&(leg.kind==='stock'||Number.isInteger(quantity))?quantity*multiple:null;
}
export function modelPayload(o){
  return {strategy:o.strategy,symbol:o.symbol,currency:o.currency,mode:o.valuation_mode,spot:num(o.spot),as_of:o.as_of||today(),target_date:o.target_date||null,
    rate:num(o.rate),dividend_yield:num(o.dividend_yield),iv_shift:num(o.iv_shift),probability_iv:num(o.probability_iv),fee_per_contract:num(o.fee_per_contract),
    range_min:num(o.range_min),range_max:num(o.range_max),scenario_price:num(o.scenario_price),capital_basis:o.financing_enabled?null:num(o.capital_basis),comparison_budget:num(o.comparison_budget),include_stock_cost:o.financing_enabled?true:o.include_stock_cost,
    financing_enabled:o.financing_enabled??false,borrowed_amount:o.financing_enabled?num(o.borrowed_amount):0,borrowing_rate:o.financing_enabled?num(o.borrowing_rate):0,financing_days:o.financing_enabled&&o.valuation_mode==='expiry'?num(o.financing_days):null,
    legs:o.legs.map(l=>({kind:l.kind,side:l.side,quantity:scaledQuantity(l,exposureMultiple(o)),multiplier:l.kind==='stock'?1:num(l.multiplier),strike:l.kind==='stock'?null:num(l.strike),premium:num(l.premium),expiration:l.kind==='stock'?null:l.expiration||null,iv:l.kind==='stock'?null:num(l.iv),contract_symbol:l.contract_symbol||''}))};
}
export function fromContract(row,side,pricing){const p=pricing==='mid'?row.mid:pricing==='last'?row.last:row[side==='buy'?'ask':'bid'];return {...blankLeg(row.kind,side),strike:String(row.strike),premium:p===null?'':String(p),expiration:row.expiration,iv:row.iv>0&&row.iv<=500?String(row.iv):'',multiplier:row.multiplier===null?'':String(row.multiplier),contract_symbol:row.contract_symbol,quote_note:`${pricing==='mid'?'Bid/ask midpoint':pricing==='last'?'Last trade':side==='buy'?'Ask':'Bid'} · trade ${row.last_trade||'time unavailable'}`};}
export const setupKeys=['exposure_multiplier','financing_enabled','borrowed_amount','borrowing_rate','financing_days','strategy','symbol','valuation_mode','currency','spot','as_of','target_date','rate','dividend_yield','iv_shift','probability_iv','fee_per_contract','capital_basis','comparison_budget','include_stock_cost','show_stock','output','result_view','scenario_name','range_min','range_max','scenario_price','legs'];
export const setupSnapshot=o=>Object.fromEntries(setupKeys.map(k=>[k,structuredClone(o[k])]));
